name: Tech News Telegram Bot

on:
  schedule:
    # Runs every hour (at the beginning of the hour)
    # You can change this. Use crontab syntax: https://crontab.guru/
    - cron: '5 */2 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
      run-news-bot:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
          - name: Check out repository
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.10'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Run Python script
            env:
              TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
              TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
              RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
            run: python news_bot.py

          - name: Commit and push state file
            run: |
              git config --global user.name 'github-actions[bot]'
              git config --global user.email 'github-actions[bot]@users.noreply.github.com'
              git add last_article_link.txt
              git diff --staged --quiet || git commit -m "Update last processed article link"
              git push
