name: Tech News Telegram Bot

on:
  schedule:
    # Runs every hour (at the beginning of the hour)
    # You can change this. Use crontab syntax: https://crontab.guru/
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  run-news-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit the state file back to the repo
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # You can choose other versions like 3.9, 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
         
          - name: Download NLTK 'punkt' resource
            run: python -m nltk.downloader punkt

      - name: Run Python script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }} # Will use default in script if not set
        run: python news_bot.py

      - name: Commit and push state file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add last_article_link.txt # The state file your script creates/updates
          # Commit only if there are changes to the state file
          git diff --staged --quiet || git commit -m "Update last processed article link"
          git push
