name: Tech News Telegram Bot

on:
  schedule:
    # Runs every hour (at the beginning of the hour)
    # You can change this. Use crontab syntax: https://crontab.guru/
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
      run-news-bot:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
          - name: Check out repository
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.10'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Download NLTK 'punkt' resource
            run: |
              python -c "
              import nltk
              import os
              nltk_data_dir = os.path.join(os.path.expanduser('~'), 'nltk_data')
              os.makedirs(nltk_data_dir, exist_ok=True) # Ensure base directory /home/runner/nltk_data exists
              if nltk_data_dir not in nltk.data.path:
                  nltk.data.path.insert(0, nltk_data_dir) # Add to front of NLTK's search path
              print(f'NLTK data path configured to: {nltk.data.path}')
              print('Attempting to download NLTK punkt...')
              nltk.download('punkt') # Let NLTK download to the configured path
              print('NLTK punkt download attempt finished.')
              "
              echo "--- Verifying NLTK punkt resource location ---"
              echo "Expected location for English pickle: /home/runner/nltk_data/tokenizers/punkt/english.pickle"
              if [ -f "/home/runner/nltk_data/tokenizers/punkt/english.pickle" ]; then
                  echo "SUCCESS: english.pickle found at expected location."
                  echo "Listing contents of /home/runner/nltk_data/tokenizers/punkt/:"
                  ls -la "/home/runner/nltk_data/tokenizers/punkt/"
              else
                  echo "ERROR: english.pickle NOT found at expected location."
                  echo "Investigating directory structure..."
                  echo "Listing /home/runner/nltk_data/ :"
                  ls -la /home/runner/nltk_data/
                  echo "Listing /home/runner/nltk_data/tokenizers/ (if exists):"
                  ls -la /home/runner/nltk_data/tokenizers/ || echo "/home/runner/nltk_data/tokenizers/ not found"
              fi
          - name: Run Python script
            env:
              TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
              TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
              RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
            run: python news_bot.py

          - name: Commit and push state file
            run: |
              git config --global user.name 'github-actions[bot]'
              git config --global user.email 'github-actions[bot]@users.noreply.github.com'
              git add last_article_link.txt
              git diff --staged --quiet || git commit -m "Update last processed article link"
              git push
